apiVersion: v1
kind: Service
metadata:
  name: notifications-load-balancer
  labels:
    app: notifications-load-balancer
  namespace: mantogin-hw7
spec:
  selector:
    app: notifications-app
  ports:
    - protocol: TCP
      name: metrics
      port: 8002
      targetPort: 8002
  type: LoadBalancer