apiVersion: v1
kind: Service
metadata:
  name: order-load-balancer
  labels:
    app: order-load-balancer
  namespace: mantogin-hw7
spec:
  selector:
    app: order-app
  ports:
    - protocol: TCP
      name: metrics
      port: 8003
      targetPort: 8003
  type: LoadBalancer